import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.scss";

const font = Jost({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fresh Lobster",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body className={font.className}>{children}</body>
    </html>
  );
}
