backend:
  name: test-repo
  branch: main

local_backend: true

logo_url: "https://coalmarketing.cz/wp-content/uploads/2024/08/coalmarketing_logo_long_color-black-1024x239.png"
locale: "en"

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "films"
    label: "Films"
    folder: "content/films"
    create: true
    slug: "{{slug}}"
    preview: true
    fields:
      - { name: "title", label: "Title" }
      - { name: "release_date", label: "Release Date", widget: "datetime" }
      - { name: "synopsis", label: "Synopsis", widget: "text" }
      - { name: "poster", label: "Poster Image", widget: "image" }
      - { name: "trailer_url", label: "Trailer URL", widget: "string", required: false }
      - { name: "draft", label: "Draft", widget: "boolean", default: false }
      - { name: "body", label: "Details / Director's Notes", widget: "markdown" }
