backend:
  name: git-gateway
  branch: main

local_backend: true

logo_url: "https://coalmarketing.cz/wp-content/uploads/2024/08/coalmarketing_logo_long_color-black-1024x239.png"
locale: "cs"

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "films"
    label: "Filmy / Projekty"
    folder: "content/films"
    create: true
    slug: "{{slug}}"
    preview: true
    fields:
      - { name: "poster", label: "Plakát", widget: "image" }
      - { name: "still", label: "Snímek", widget: "image" }
      - { name: "title", label: "Název projektu / filmu / seriálu" }
      - { name: "release_year", label: "Rok zveřejnění", widget: "number" }
      - { name: "director", label: "Režie" }
      - { name: "screenplay", label: "Scénář" }
      - { name: "camera", label: "Kamera" }
      - { name: "music", label: "Hudba" }
      - { name: "collaborators", label: "Spolupracovali", widget: "list", field: { name: "name", label: "Jméno" } }
      - { name: "cast", label: "Hrají", widget: "list", field: { name: "name", label: "Jméno" } }
      - { name: "short_synopsis", label: "Krátká synopse", widget: "text" }
      - { name: "long_synopsis", label: "Dlouhá synopse", widget: "text" }
      - { name: "details", label: "Podrobnosti", widget: "markdown" }
      - { name: "downloads", label: "Ke stažení", widget: "list", field: { name: "file", label: "Soubor", widget: "file" } }
      - { name: "trailer_url", label: "YouTube iframe s trailerem", widget: "string", required: false }
      - { name: "draft", label: "Je koncept?", widget: "boolean", default: false }

  - name: "people"
    label: "Spolupracovníci"
    folder: "content/people"
    create: true
    slug: "{{slug}}"
    preview: true
    fields:
      - { name: "name", label: "Jméno" }
      - { name: "photo", label: "Fotografie", widget: "image" }
      - { name: "role", label: "Role", widget: "string" }
      - { name: "projects", label: "Spolupracoval/a na projektech", widget: "list", field: { name: "name", label: "Jméno" } }
      - { name: "draft", label: "Je koncept?", widget: "boolean", default: false }
